import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { attachPageDiagnostics, dismissOnboarding, waitForAppReady } from './support.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const registry = JSON.parse(readFileSync(join(__dirname, '../../data/template-registry.json'), 'utf8'));

const DISCLAIMER_SNIPPET = 'open-source reference tool';

function escapeRegex(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

test.beforeEach(async ({ page }) => {
  attachPageDiagnostics(page);
});

for (const template of registry.templates) {
  test(`generates download for ${template.display_name}`, async ({ page }) => {
    await page.goto('/?view=templates');
    await waitForAppReady(page);
    await dismissOnboarding(page);

    const card = page
      .locator('#companion-templates')
      .getByRole('button', { name: new RegExp(`^${escapeRegex(template.display_name)}\\b`) });
    await card.click();
    await expect(page.getByText('What this template is for')).toBeVisible();
    await expect(page).toHaveURL(new RegExp(`templateType=${template.name}`));

    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: new RegExp(`Generate ${template.display_name}`) }).click();
    const download = await downloadPromise;

    expect(download.suggestedFilename()).toMatch(new RegExp(`${template.name.replace(/_/g, '-')}-\\d{4}-\\d{2}-\\d{2}\\.`));
    const downloadPath = await download.path();
    expect(downloadPath).toBeTruthy();
    const content = readFileSync(downloadPath, 'utf8');
    expect(content.toLowerCase()).toContain(DISCLAIMER_SNIPPET);
    expect(content).toMatch(/Source Metadata|Framework context|Reference sources|Generated by Control Atlas/);
  });
}

test('deep link pre-selects security plan starter', async ({ page }) => {
  await page.goto('/?view=templates&templateType=security_plan_starter');
  await waitForAppReady(page);
  await dismissOnboarding(page);
  await expect(page.getByText('What this template is for')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Generate Security Plan Starter' })).toBeVisible();
});

test('format change updates download extension', async ({ page }) => {
  await page.goto('/?view=templates&templateType=inheritance_worksheet');
  await waitForAppReady(page);
  await dismissOnboarding(page);

  await page.getByRole('button', { name: 'More options' }).click();
  await page.getByLabel('Format').selectOption('csv');

  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Generate Inheritance Worksheet' }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toMatch(/\.csv$/);
});

// CATL-73: office-format export runs entirely client-side. A downloaded file
// that starts with the ZIP local-file-header magic ("PK\x03\x04") is a real
// OOXML package, not a text stub.
async function assertZipDownload(download) {
  const path = await download.path();
  expect(path).toBeTruthy();
  const bytes = readFileSync(path);
  expect(bytes.length).toBeGreaterThan(0);
  expect(bytes[0]).toBe(0x50); // P
  expect(bytes[1]).toBe(0x4b); // K
  expect(bytes[2]).toBe(0x03);
  expect(bytes[3]).toBe(0x04);
}

test('tabular template exports a real .xlsx workbook client-side', async ({ page }) => {
  await page.goto('/?view=templates&templateType=poam_starter');
  await waitForAppReady(page);
  await dismissOnboarding(page);

  await page.getByRole('button', { name: 'More options' }).click();
  await page.locator("#field-format").selectOption("xlsx");

  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Generate POA&M Working Register' }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toMatch(/\.xlsx$/);
  await assertZipDownload(download);
});

test('SSP starter exports a real .docx document client-side', async ({ page }) => {
  await page.goto('/?view=templates&templateType=security_plan_starter');
  await waitForAppReady(page);
  await dismissOnboarding(page);

  await page.getByRole('button', { name: 'More options' }).click();
  await page.locator("#field-format").selectOption("docx");

  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Generate Security Plan Starter' }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toMatch(/\.docx$/);
  await assertZipDownload(download);
});
