import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { attachPageDiagnostics, dismissOnboarding, waitForAppReady } from './support.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const registry = JSON.parse(readFileSync(join(__dirname, '../../data/template-registry.json'), 'utf8'));

const DISCLAIMER_SNIPPET = 'open-source reference tool';

test.beforeEach(async ({ page }) => {
  attachPageDiagnostics(page);
});

for (const template of registry.templates) {
  test(`generates download for ${template.display_name}`, async ({ page }) => {
    await page.goto('/?view=templates');
    await waitForAppReady(page);
    await dismissOnboarding(page);

    const card = page.locator('.intent-card').filter({ hasText: template.display_name });
    await card.getByRole('button', { name: 'Choose artifact' }).click();
    await expect(page.getByText('What this template is for')).toBeVisible();
    await expect(page).toHaveURL(new RegExp(`templateType=${template.name}`));

    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Generate template' }).click();
    const download = await downloadPromise;

    expect(download.suggestedFilename()).toMatch(new RegExp(`${template.name.replace(/_/g, '-')}-\\d{4}-\\d{2}-\\d{2}\\.`));
    const downloadPath = await download.path();
    expect(downloadPath).toBeTruthy();
    const content = readFileSync(downloadPath, 'utf8');
    expect(content.toLowerCase()).toContain(DISCLAIMER_SNIPPET);
    expect(content).toMatch(/Source Metadata|Framework context|Reference sources|Generated by Control Atlas/);
  });
}

test('deep link pre-selects security plan starter', async ({ page }) => {
  await page.goto('/?view=templates&templateType=security_plan_starter');
  await waitForAppReady(page);
  await dismissOnboarding(page);
  await expect(page.getByText('What this template is for')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Generate template' })).toBeVisible();
});

test('format change updates download extension', async ({ page }) => {
  await page.goto('/?view=templates&templateType=inheritance_worksheet');
  await waitForAppReady(page);
  await dismissOnboarding(page);

  await page.getByRole('button', { name: 'More options' }).click();
  await page.getByLabel('Format').selectOption('csv');

  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Generate template' }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toMatch(/\.csv$/);
});
