import assert from 'node:assert/strict';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import test from 'node:test';
import { COMPLETENESS_STATES, resolveExpectedLocator, classifyCatalog } from '../scripts/lib/completeness.mjs';

// --- resolveExpectedLocator: authoritative expected count from a locator ---

test('resolveExpectedLocator reads an integer at a dotted JSON path', () => {
  const readJson = (rel) => (rel === 'x.json' ? { reconciliation: { stig_records_parsed: 17360 } } : null);
  assert.equal(resolveExpectedLocator('x.json#reconciliation.stig_records_parsed', readJson), 17360);
});

test('resolveExpectedLocator returns null for a non-integer, missing path, or malformed locator', () => {
  const readJson = () => ({ a: { b: 'not-a-number' } });
  assert.equal(resolveExpectedLocator('x.json#a.b', readJson), null);
  assert.equal(resolveExpectedLocator('x.json#a.missing', readJson), null);
  assert.equal(resolveExpectedLocator('no-hash-here', readJson), null);
  assert.equal(resolveExpectedLocator('x.json#a.b', () => null), null);
});

// --- classifyCatalog: honest completeness states (spec §1) ---

test('reconciled requires an integer expectation that closes to zero with real checksums', () => {
  const r = classifyCatalog({ expected: 100, imported: 90, excluded: 10, allChecksumsReal: true, primaryQuarantined: false });
  assert.equal(r.status, 'reconciled');
  assert.equal(r.missing, 0);
  assert.deepEqual(r.errors, []);
});

test('partial when records are still missing against a known expectation', () => {
  const r = classifyCatalog({ expected: 17360, imported: 615, excluded: 0, allChecksumsReal: true, primaryQuarantined: false });
  assert.equal(r.status, 'partial');
  assert.equal(r.missing, 16745);
});

test('discovered when records exist but no authoritative expectation is established', () => {
  assert.equal(classifyCatalog({ expected: null, imported: 135, excluded: 0, allChecksumsReal: true, primaryQuarantined: false }).status, 'discovered');
});

test('unknown when there are neither records nor an expectation', () => {
  assert.equal(classifyCatalog({ expected: null, imported: 0, excluded: 0, allChecksumsReal: false, primaryQuarantined: false }).status, 'unknown');
});

test('quarantined when the primary evidence is quarantined and nothing imported', () => {
  assert.equal(classifyCatalog({ expected: null, imported: 0, excluded: 0, allChecksumsReal: false, primaryQuarantined: true }).status, 'quarantined');
});

test('a full inventory with unreal checksums cannot be reconciled', () => {
  const r = classifyCatalog({ expected: 50, imported: 50, excluded: 0, allChecksumsReal: false, primaryQuarantined: false });
  assert.equal(r.status, 'partial');
});

test('over-count (imported+excluded exceed expected) flags an inventory error', () => {
  const r = classifyCatalog({ expected: 10, imported: 12, excluded: 0, allChecksumsReal: true, primaryQuarantined: false });
  assert.equal(r.status, 'partial');
  assert.ok(r.errors.includes('inventory-over-count'));
});

// --- integration: the committed coverage manifest obeys the reconciled invariant ---

test('no committed catalog is reconciled with an unknown expected/missing inventory', () => {
  const path = 'data/source-coverage-manifest.json';
  if (!existsSync(path)) return; // generated by verify:manifests; skip if not yet built
  const coverage = JSON.parse(readFileSync(path, 'utf8'));
  for (const c of coverage.catalogs || []) {
    assert.ok(COMPLETENESS_STATES.includes(c.completeness_status), `unknown state: ${c.completeness_status}`);
    if (c.completeness_status === 'reconciled') {
      assert.ok(Number.isInteger(c.expected_records), `${c.catalog_id} reconciled with null expected_records`);
      assert.ok(Number.isInteger(c.missing_records), `${c.catalog_id} reconciled with null missing_records`);
      assert.equal(c.missing_records, 0, `${c.catalog_id} reconciled with missing_records != 0`);
      assert.equal(c.expected_records, c.imported_records + c.excluded_records + c.missing_records,
        `${c.catalog_id} reconciled but expected != imported + excluded + missing`);
    }
  }
});

test('every generated catalog participates in the source coverage model', () => {
  const coverage = JSON.parse(readFileSync('data/source-coverage-manifest.json', 'utf8'));
  const generated = readdirSync('data/generated/catalog-records', { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.json'))
    .map((entry) => entry.name.slice(0, -5))
    .sort();
  const covered = coverage.catalogs.map((catalog) => catalog.catalog_id).sort();
  assert.deepEqual(covered, generated);
  assert.ok(coverage.catalogs.every((catalog) => ['reconciled', 'discovered', 'partial', 'quarantined'].includes(catalog.completeness_status)),
    'a shipped catalog with records cannot be coverage-unknown');
});

test('active canonical source layers never retain manual-seed provenance', () => {
  const registry = JSON.parse(readFileSync('data/source-registry.json', 'utf8'));
  for (const layer of ['publications', 'sources', 'artifacts']) {
    for (const record of registry[layer] || []) {
      if (record.lifecycle_status === 'active' || record.graph_eligible === true) {
        assert.notEqual(record.parser || record.metadata?.parser, 'manual-seed', `${layer}:${record.id}`);
      }
    }
  }
});
