import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { generateTemplate } from '../src/app/template-engine.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const registry = JSON.parse(readFileSync(join(__dirname, '../data/template-registry.json'), 'utf8'));

const DISCLAIMER_SNIPPET = 'open-source reference tool';
const SOURCE_METADATA_MARKERS = ['Source Metadata', 'Framework context', 'Reference sources', 'Generated by Control Atlas'];

const dataset = {
  nodes: [
    {
      id: 'nist-800-53:AC-2',
      node_type: 'control',
      label: 'AC-2 Account Management',
      metadata: {
        catalog_id: 'nist-800-53',
        item_id: 'AC-2',
        title: 'Account Management',
        control_family: 'Access Control',
      },
    },
  ],
  sources: [
    {
      id: 'nist-oscal',
      display_name: 'SP 800-53 Rev. 5',
      version: '2026-06-09',
    },
  ],
};

function assertDisclaimer(content, format) {
  assert.match(content, new RegExp(DISCLAIMER_SNIPPET, 'i'), `Missing disclaimer in ${format}`);
  if (format === 'csv') {
    assert.match(content, /# Disclaimer:/, `CSV missing disclaimer comment in ${format}`);
  }
  if (format === 'json') {
    assert.match(content, /"disclaimer"/, `JSON missing disclaimer field in ${format}`);
  }
  if (format === 'yaml') {
    assert.match(content, /^disclaimer:/m, `YAML missing disclaimer key in ${format}`);
  }
  if (format === 'markdown') {
    assert.match(content, />\s*\*\*Disclaimer:\*\*/, `Markdown missing disclaimer blockquote in ${format}`);
  }
}

function assertSourceMetadata(content, format) {
  const hasMarker = SOURCE_METADATA_MARKERS.some((marker) => content.includes(marker));
  assert.ok(hasMarker, `Missing source metadata in ${format}`);
  if (format === 'csv') {
    assert.match(content, /# Source Metadata:/, `CSV missing source metadata comment in ${format}`);
  }
}

for (const template of registry.templates) {
  for (const format of template.supported_formats) {
    test(`export contract: ${template.name} (${format}) includes disclaimer and source metadata`, () => {
      const result = generateTemplate(
        {
          templateType: template.name,
          framework: 'nist-800-53',
          environment: 'Cloud SaaS',
          format,
          sourceRefs: template.source_refs || [],
          sources: dataset.sources,
        },
        dataset,
      );

      assert.ok(result.content.length > 0, 'Generated content is empty');
      assert.ok(result.filename.endsWith(`.${format === 'markdown' ? 'md' : format}`), `Unexpected filename: ${result.filename}`);
      assertDisclaimer(result.content, format);
      assertSourceMetadata(result.content, format);
    });
  }
}

test('all nine templates are registered', () => {
  assert.equal(registry.templates.length, 9);
});

test('registry templates have non-empty source_refs', () => {
  for (const template of registry.templates) {
    assert.ok(Array.isArray(template.source_refs), `${template.name} missing source_refs`);
    assert.ok(template.source_refs.length > 0, `${template.name} has empty source_refs`);
  }
});
