export const glossaryData = [
  {
    id: "ato",
    term: "ATO",
    expansion: "Authorization to Operate",
    definition: "The official management decision given by a senior federal official (the Authorizing Official) to authorize operation of an information system and to explicitly accept the risk to agency operations.",
    why_it_matters: "Without an ATO, a system cannot legally process data or go live — this signature is what makes operation official.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["rmf-lifecycle", "ato-vs-atc", "ato-vs-fedramp"],
    related_controls: ["PL-2", "SA-9"]
  },
  {
    id: "atc",
    term: "ATC",
    expansion: "Authority to Connect",
    definition: "The official management decision to allow an information system to connect to a specific network or enclave based on compliance with security requirements.",
    why_it_matters: "An ATO alone doesn't let a system talk to a network; the ATC is the separate approval that governs connections between systems.",
    source: "Practitioner-consensus",
    consensus: true,
    related_patterns: ["ato-vs-atc", "boundary-patterns"],
    related_controls: ["CA-3", "CA-9"]
  },
  {
    id: "fedramp-authorization",
    term: "FedRAMP authorization",
    expansion: "Federal Risk and Authorization Management Program Authorization",
    definition: "A government-wide program that provides a standardized approach to security assessment, authorization, and continuous monitoring for cloud products and services.",
    why_it_matters: "One FedRAMP authorization can be reused by many federal agencies, which is what avoids repeating a full assessment for every customer.",
    source: "FedRAMP Program Management Office",
    consensus: false,
    related_patterns: ["ato-vs-fedramp", "csp-inheritance"],
    related_controls: ["CA-2", "PL-2"]
  },
  {
    id: "rmf",
    term: "RMF",
    expansion: "Risk Management Framework",
    definition: "A structured process that integrates security, privacy, and cyber risk management activities into the system development life cycle.",
    why_it_matters: "Nearly every other term in this glossary — SSPs, SARs, POA&Ms, ATOs — is a step or artifact inside this one process.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["rmf-lifecycle", "poam-concepts"],
    related_controls: ["PL-2", "CA-2"]
  },
  {
    id: "stig",
    term: "STIG",
    expansion: "Security Technical Implementation Guide",
    definition: "A cybersecurity technical standard created by the Defense Information Systems Agency (DISA) to secure specific software, hardware, or network components.",
    why_it_matters: "STIGs turn a broad control requirement into a specific, checkable configuration setting an administrator can actually apply.",
    source: "DISA Cybersecurity Program",
    consensus: false,
    related_patterns: ["evidence-patterns", "rmf-lifecycle"],
    related_controls: ["CM-6", "SI-2"]
  },
  {
    id: "srg",
    term: "SRG",
    expansion: "Security Requirements Guide",
    definition: "High-level security requirement standards published by DISA that define security criteria for a technology area (e.g., application server, OS).",
    why_it_matters: "When no STIG exists yet for a specific product, the SRG for its technology family is the fallback standard to build from.",
    source: "DISA Cybersecurity Program",
    consensus: false,
    related_patterns: ["evidence-patterns"],
    related_controls: ["CM-6"]
  },
  {
    id: "cci",
    term: "CCI",
    expansion: "Control Correlation Identifier",
    definition: "A standard identifier that decomposes high-level security controls (like NIST SP 800-53) into granular, low-level technical specifications.",
    why_it_matters: "CCIs are the bridge that lets a technical STIG check trace back to the specific NIST control it satisfies.",
    source: "DISA Cybersecurity Program",
    consensus: false,
    related_patterns: ["evidence-patterns"],
    related_controls: ["CM-6"]
  },
  {
    id: "sar",
    term: "SAR",
    expansion: "Security Assessment Report",
    definition: "A document containing the results of testing and evaluating the security controls of an information system, detailing any vulnerabilities found.",
    why_it_matters: "The SAR is the document an Authorizing Official actually reads to decide whether to accept the system's risk.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["boe-reuse", "reciprocity-basics"],
    related_controls: ["CA-2", "CA-5"]
  },
  {
    id: "sap",
    term: "SAP",
    expansion: "Security Assessment Plan",
    definition: "A document detailing the objectives, scope, methodology, schedule, and procedures to be used during the security control assessment.",
    why_it_matters: "Agreeing the SAP before testing starts is what prevents disputes later about what was in or out of scope.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["evidence-patterns", "rmf-lifecycle"],
    related_controls: ["CA-2"]
  },
  {
    id: "ssp",
    term: "SSP",
    expansion: "System Security Plan",
    definition: "A comprehensive description of a system's boundary, operational environment, and the controls implemented to meet compliance requirements.",
    why_it_matters: "The SSP is the single source of truth assessors compare the running system against during every review.",
    source: "NIST SP 800-18 Rev. 1",
    consensus: false,
    related_patterns: ["rmf-lifecycle", "shared-responsibility"],
    related_controls: ["PL-2"]
  },
  {
    id: "poam",
    term: "POA&M",
    expansion: "Plan of Action and Milestones",
    definition: "A document that identifies tasks to be accomplished to remediate vulnerabilities or compliance gaps identified during assessments.",
    why_it_matters: "A POA&M turns an assessment finding into a tracked commitment with an owner and a deadline, instead of a finding that quietly disappears.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["poam-concepts", "rmf-lifecycle"],
    related_controls: ["CA-5", "PM-4"]
  },
  {
    id: "boe",
    term: "BoE",
    expansion: "Body of Evidence",
    definition: "The collective set of document and system artifacts (SSPs, logs, policies, test results) demonstrating that security controls are properly implemented.",
    why_it_matters: "Assessors don't take control implementation on faith — the BoE is the evidence they check every SSP claim against.",
    source: "Practitioner-consensus",
    consensus: true,
    related_patterns: ["boe-reuse", "evidence-patterns"],
    related_controls: ["CA-2", "CA-5"]
  },
  {
    id: "reciprocity",
    term: "reciprocity",
    expansion: "Reciprocity",
    definition: "The mutual agreement to accept another organization's security assessment results, reducing redundant testing and accelerating authorizations.",
    why_it_matters: "Reciprocity is why a system already authorized by one agency doesn't need a from-scratch reassessment before another agency can use it.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["reciprocity-basics", "reciprocity-failures", "boe-reuse"],
    related_controls: ["CA-2", "SA-9"]
  },
  {
    id: "inheritance",
    term: "inheritance",
    expansion: "Control Inheritance",
    definition: "The capability of a system to inherit security controls implemented by an external provider or hosting platform, reducing local implementation effort.",
    why_it_matters: "Correctly claiming inheritance keeps a system's own SSP from duplicating controls an external provider already implements.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["control-inheritance", "common-control-provider", "csp-inheritance", "enterprise-inheritance"],
    related_controls: ["PL-2", "SA-9"]
  },
  {
    id: "common-control",
    term: "common control",
    expansion: "Common Control",
    definition: "A security control that is inherited by multiple information systems and managed by a centralized common control provider.",
    why_it_matters: "Common controls let an organization implement a control once and have every system in its inventory inherit it, instead of re-implementing it per system.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["common-control-provider", "control-inheritance"],
    related_controls: ["PL-2"]
  },
  {
    id: "shared-responsibility",
    term: "shared responsibility",
    expansion: "Shared Responsibility Model",
    definition: "A compliance framework dividing security obligations between the infrastructure/platform provider and the customer system owner.",
    why_it_matters: "Misreading this boundary is one of the most common ways a control gets marked implemented when it's actually the provider's job, or vice versa.",
    source: "Practitioner-consensus",
    consensus: true,
    related_patterns: ["shared-responsibility", "control-inheritance", "csp-inheritance"],
    related_controls: ["PL-2", "SA-9"]
  },
  {
    id: "isso",
    term: "ISSO",
    expansion: "Information System Security Officer",
    definition: "An individual responsible for ensuring that the appropriate operational security posture is maintained for an information system.",
    why_it_matters: "The ISSO is usually the day-to-day contact keeping the SSP and POA&M current between formal assessments.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["rmf-lifecycle"],
    related_controls: ["PL-2"]
  },
  {
    id: "issm",
    term: "ISSM",
    expansion: "Information System Security Manager",
    definition: "A senior role responsible for managing an organization's overall cybersecurity program and supervising Information System Security Officers.",
    why_it_matters: "The ISSM owns security posture across an entire program, one level above the per-system ISSO role.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["rmf-lifecycle"],
    related_controls: ["PL-2"]
  },
  {
    id: "sca",
    term: "SCA",
    expansion: "Security Control Assessor",
    definition: "An independent individual or team responsible for testing, evaluating, and determining the effectiveness of security controls.",
    why_it_matters: "The SCA's independence from the system team is what gives the assessment result credibility with the Authorizing Official.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["evidence-patterns", "rmf-lifecycle"],
    related_controls: ["CA-2"]
  },
  {
    id: "ao",
    term: "AO",
    expansion: "Authorizing Official",
    definition: "A senior federal official with the authority to formally assume responsibility for operating an information system at an acceptable level of risk.",
    why_it_matters: "The AO is the one person whose signature creates legal accountability for accepting the system's risk.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["rmf-lifecycle", "ato-vs-fedramp", "ato-vs-atc"],
    related_controls: ["PL-2"]
  },
  {
    id: "aodr",
    term: "AODR",
    expansion: "Authorizing Official Designated Representative",
    definition: "An individual designated by the Authorizing Official to carry out necessary tasks and duties associated with security authorization activities.",
    why_it_matters: "An AODR lets routine authorization decisions move faster without the AO personally reviewing every one of them.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["rmf-lifecycle"],
    related_controls: ["PL-2"]
  },
  {
    id: "boundary",
    term: "boundary",
    expansion: "Authorization Boundary",
    definition: "All components of an information system to be authorized for operation by an Authorizing Official, excluding external services.",
    why_it_matters: "Drawing the boundary too broadly adds controls that don't need assessing; drawing it too narrowly hides risk outside the authorization.",
    source: "NIST SP 800-37 Rev. 2",
    consensus: false,
    related_patterns: ["boundary-patterns"],
    related_controls: ["PL-2"]
  },
  {
    id: "overlay",
    term: "overlay",
    expansion: "Security Control Overlay",
    definition: "A specification of security controls, enhancements, and guidance tailored for a specific technology area, industry, or operational mission.",
    why_it_matters: "Overlays let a baseline adjust for a specific context, like cloud or privacy, without redefining the entire control catalog.",
    source: "NIST SP 800-53 Rev. 5",
    consensus: false,
    related_patterns: ["boundary-patterns", "reciprocity-basics"],
    related_controls: ["PL-2"]
  },
  {
    id: "baseline",
    term: "baseline",
    expansion: "Security Control Baseline",
    definition: "A starting set of security and privacy controls designated for a system based on its impact level (Low, Moderate, High).",
    why_it_matters: "The baseline is what determines which controls apply at all — most control-selection disagreements trace back to which baseline was picked.",
    source: "NIST SP 800-53 Rev. 5",
    consensus: false,
    related_patterns: ["rmf-lifecycle", "boundary-patterns"],
    related_controls: ["PL-2"]
  },
  {
    id: "profile",
    term: "profile",
    expansion: "Security Control Profile",
    definition: "A customized set of security controls selected from a baseline to address specific mission objectives or regulatory requirements.",
    why_it_matters: "A profile is how an organization tailors a baseline to its own mission instead of applying every control exactly as written.",
    source: "NIST SP 800-53 Rev. 5",
    consensus: false,
    related_patterns: ["boundary-patterns"],
    related_controls: ["PL-2"]
  },
  {
    id: "continuous-monitoring",
    term: "continuous monitoring",
    expansion: "Continuous Monitoring",
    definition: "The ongoing assessment and report of security control effectiveness and system posture to support authorization decisions.",
    why_it_matters: "ConMon is what keeps an ATO valid between full reauthorization cycles instead of relying on a point-in-time snapshot.",
    source: "NIST SP 800-137",
    consensus: false,
    related_patterns: ["conmon-cadence", "rmf-lifecycle"],
    related_controls: ["CA-7"]
  },
  {
    id: "li-saas",
    term: "LI-SaaS",
    expansion: "Low-Impact Software as a Service",
    definition: "A streamlined FedRAMP baseline for cloud services that handle low-risk, publicly available data and meet a narrow set of usage criteria (no PII beyond login data, no CUI).",
    why_it_matters: "LI-SaaS gives low-risk SaaS products a lighter authorization path instead of the full FedRAMP Low baseline, which most of them don't need.",
    source: "FedRAMP Program Management Office",
    consensus: false,
    related_patterns: ["ato-vs-fedramp"],
    related_controls: ["CA-2"]
  },
  {
    id: "cui",
    term: "CUI",
    expansion: "Controlled Unclassified Information",
    definition: "Information the government creates or possesses that requires safeguarding under law, regulation, or policy, but is not classified national security information.",
    why_it_matters: "CUI is the sensitivity tier that pulls a system into 800-171/CMMC requirements even when it never touches classified data.",
    source: "32 CFR Part 2002 (ISOO CUI Program)",
    consensus: false,
    related_patterns: ["reciprocity-basics"],
    related_controls: ["AC-2"]
  },
  {
    id: "csp",
    term: "CSP",
    expansion: "Cloud Service Provider",
    definition: "A company that offers cloud computing services (infrastructure, platform, or software) that a federal system may run on or consume.",
    why_it_matters: "Which controls a system inherits versus implements itself usually traces back to what the CSP already covers under the shared responsibility model.",
    source: "FedRAMP Program Management Office",
    consensus: false,
    related_patterns: ["csp-inheritance", "shared-responsibility"],
    related_controls: ["SA-9"]
  }
];
