/**
 * @typedef {Object} TextSection
 * @property {"text"} type
 * @property {string} heading
 * @property {string} content
 *
 * @typedef {Object} TableSection
 * @property {"table"} type
 * @property {string} heading
 * @property {string[]} headers
 * @property {any[][]} rows
 *
 * @typedef {TextSection | TableSection} DocSection
 *
 * @typedef {Object} TemplateDocument
 * @property {string} title
 * @property {string} description
 * @property {DocSection[]} sections
 */

const DISCLAIMER = "Control Atlas is an open-source reference tool. It is not an official government system and does not make compliance, authorization, or risk decisions. All mappings and templates are reference aids based on public sources. Official decisions remain with the applicable Authorizing Official, agency, or program office.";

const EVIDENCE_TYPE_HINT = "Policy | Procedure | Config screenshot | System report | Access review | Scan output | Interview | Architecture diagram | Change record | Training record | Incident record | Log sample | Inventory export | Exception memo";

/** @type {Record<string, { display_name: string, version: string }>} */
const SOURCE_FALLBACK = {
  "nist-oscal": { display_name: "SP 800-53 Rev. 5", version: "2026-06-09" },
  "disa-stig-library": { display_name: "DISA STIG Library", version: "2026-06-09" },
  "disa-cci-list": { display_name: "DISA CCI List", version: "2026-06-09" },
  "nist-800-37-rev2": { display_name: "NIST SP 800-37 Rev. 2", version: "2026-06-09" },
  "nist-sp-800-137": { display_name: "NIST SP 800-137", version: "2026-06-09" },
};

export const ENVIRONMENT_ARCHETYPES = [
  "Generic",
  "Cloud SaaS",
  "Platform service",
  "Enclave",
  "On-premises",
  "Hybrid",
  "Enterprise service",
];

/**
 * @param {{ id: string, title?: string }} control
 * @returns {string}
 */
function controlReference(control) {
  return control.title ? `${control.title} (${control.id})` : control.id;
}

/**
 * @param {any} options
 * @returns {(txt: string) => string}
 */
function placeholder(options) {
  return (txt) => (options.includePlaceholders !== false ? txt : "");
}

/**
 * @param {(string | { id: string })[]} sourceRefs
 * @param {any[]} sources
 * @returns {string[]}
 */
function resolveSourceLines(sourceRefs, sources) {
  const sourceMap = new Map((sources || []).map((s) => [s.id, s]));
  const lines = [];
  for (const ref of sourceRefs || []) {
    const id = typeof ref === "string" ? ref : ref.id;
    const src = sourceMap.get(id) || SOURCE_FALLBACK[id];
    if (src) {
      const name = src.display_name || src.name || id;
      const version = src.version || "unknown";
      lines.push(`${name} (version ${version})`);
    } else if (id) {
      lines.push(id);
    }
  }
  return lines;
}

/**
 * @param {any} options
 * @returns {string}
 */
export function buildSourceMetadata(options) {
  const lines = [];
  if (options.framework) {
    lines.push(`Framework context: ${options.framework}`);
  }
  lines.push(`Environment archetype: ${options.environment || "Generic"}`);
  const refLines = resolveSourceLines(options.sourceRefs, options.sources);
  if (refLines.length) {
    lines.push("Reference sources:");
    for (const line of refLines) {
      lines.push(`- ${line}`);
    }
  }
  lines.push("Generated by Control Atlas (reference aid only).");
  return lines.join("\n");
}

/**
 * @param {TemplateDocument} doc
 * @param {any} options
 * @returns {TemplateDocument}
 */
function appendSourceMetadata(doc, options) {
  doc.sections.push({
    type: "text",
    heading: "Source Metadata",
    content: buildSourceMetadata(options),
  });
  return doc;
}

/**
 * @param {any} options
 * @param {any[]} controls
 * @returns {TemplateDocument}
 */
function generateSecurityPlanStarter(options, controls) {
  const ph = placeholder(options);
  const env = options.environment || "Generic";

  const baselineHeaders = ["Control ID", "Control Title", "Implementation Status", "Responsible Role"];
  if (options.includeImplementationPrompts !== false) baselineHeaders.push("Implementation Prompt");
  if (options.includeEvidenceExpectations !== false) baselineHeaders.push("Evidence Expectation");
  if (options.includeInheritancePrompts !== false) baselineHeaders.push("Inheritance Prompt");
  if (options.includeReciprocityPrompts !== false) baselineHeaders.push("Reciprocity Prompt");
  if (options.includeStigReferences !== false) baselineHeaders.push("STIG References");
  baselineHeaders.push("Notes");

  const baselineRows = controls.map((c) => {
    const row = [c.id, c.title, ph("[Status]"), ph("[Role]")];
    if (options.includeImplementationPrompts !== false) {
      row.push(`How is ${controlReference(c)} implemented in the ${env} environment? Describe policies, technical controls, and who maintains them.`);
    }
    if (options.includeEvidenceExpectations !== false) {
      row.push(`What evidence would show ${controlReference(c)} is working? Name artifact types and review cadence.`);
    }
    if (options.includeInheritancePrompts !== false) {
      row.push(`Is ${controlReference(c)} inherited from a common control provider? If yes, name the provider and split responsibilities.`);
    }
    if (options.includeReciprocityPrompts !== false) {
      row.push(`Can assessment results for ${controlReference(c)} be reused at another agency? Note gaps or caveats.`);
    }
    if (options.includeStigReferences !== false) {
      row.push(ph("[Related STIG/SRG rules — list rule IDs or N/A]"));
    }
    row.push(ph("[Notes]"));
    return row;
  });

  const inheritanceHeaders = ["Control ID", "Inheritance Type", "Provider", "Customer Responsibility", "Notes"];
  const inheritanceRows = controls.slice(0, 1).map((c) => [
    c.id,
    ph("[Fully inherited | Hybrid | Not inherited]"),
    ph("[Provider name or N/A]"),
    ph("[What your team still implements locally]"),
    ph("[Notes]"),
  ]);

  const evidenceHeaders = ["Control ID", "Evidence Type", "Example Artifacts", "Review Cadence", "Notes"];
  const evidenceRows = controls.slice(0, 1).map((c) => [
    c.id,
    ph(`[${EVIDENCE_TYPE_HINT}]`),
    ph("[Name specific files, reports, or records]"),
    ph("[Annual | Quarterly | Continuous]"),
    ph("[Notes]"),
  ]);

  /** @type {DocSection[]} */
  const sections = [
    {
      type: "text",
      heading: "Title Page",
      content: ph("System name and short title — What system is this plan for? Write a name and one-line description a reviewer can use to understand scope."),
    },
    {
      type: "text",
      heading: "Document Metadata",
      content: ph("Version, date, author role, and classification — Who owns this document and when was it last updated? Use your agency's labeling rules."),
    },
    {
      type: "text",
      heading: "System Overview",
      content: ph("System purpose and mission support — What does this system do and why does it exist? Avoid jargon; explain who uses it and for what."),
    },
    {
      type: "text",
      heading: "Authorization Boundary",
      content: ph("Boundary description — What is inside the authorization boundary? List major components, data flows, and what is explicitly out of scope."),
    },
    {
      type: "text",
      heading: "System Environment",
      content: `Environment archetype: ${env}. Describe hosting, deployment model, and shared services that affect control implementation.`,
    },
    {
      type: "text",
      heading: "Data Types",
      content: ph("Data handled — What types of data does the system process or store? Note sensitivity levels (e.g., CUI, PII) and retention expectations."),
    },
    {
      type: "text",
      heading: "User Roles",
      content: ph("Roles and privileges — Who uses the system (admin, operator, end user)? Describe access levels and separation of duties."),
    },
    {
      type: "text",
      heading: "Interconnections",
      content: ph("External connections — What other systems connect to this one? Note direction of data flow and security agreements."),
    },
    { type: "table", heading: "Control Baseline", headers: baselineHeaders, rows: baselineRows },
    { type: "table", heading: "Inheritance Summary", headers: inheritanceHeaders, rows: inheritanceRows },
    { type: "table", heading: "Evidence Expectations", headers: evidenceHeaders, rows: evidenceRows },
    {
      type: "text",
      heading: "Revision History",
      content: ph("Version | Date | Author role | Summary of changes — Track updates so reviewers know what changed since the last review."),
    },
  ];

  return appendSourceMetadata(
    {
      title: "System Security Plan (SSP) Starter",
      description: "Blank planning structure for a system security plan.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @param {any[]} controls
 * @returns {TemplateDocument}
 */
function generateImplementationStatementWorksheet(options, controls) {
  const ph = placeholder(options);
  const headers = [
    "Control ID",
    "Control Title",
    "Implementation Statement",
    "Evidence Type Hint",
    "Responsible Role",
    "Implementation Prompt",
    "Status",
  ];

  const rows = controls.map((c) => [
    c.id,
    c.title,
    ph("[Draft statement — describe how this control is implemented]"),
    ph(`[${EVIDENCE_TYPE_HINT}]`),
    ph("[Role responsible for maintaining this control]"),
    `Describe the technical controls, policies, or mechanisms implementing ${controlReference(c)}. Include who operates them and how often they are reviewed.`,
    ph("[Draft | Reviewed | Approved]"),
  ]);

  /** @type {DocSection[]} */
  const sections = [{ type: "table", heading: "Implementation Statements", headers, rows }];

  return appendSourceMetadata(
    {
      title: "Control Implementation Statement Worksheet",
      description: "Worksheet to draft control implementation statements.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @param {any[]} controls
 * @returns {TemplateDocument}
 */
function generateEvidenceExpectationMatrix(options, controls) {
  const ph = placeholder(options);
  const headers = [
    "Control ID",
    "Control Title",
    "Control Family",
    "Related STIG/SRG",
    "Related CCI",
    "Evidence Type",
    "Example Artifact Names",
    "Suggested Owner Role",
    "Review Cadence",
    "Notes",
    "Source",
    "Confidence",
  ];

  const rows = controls.map((c) => [
    c.id,
    c.title,
    c.family || "",
    ph("[STIG/SRG rule IDs or N/A]"),
    ph("[CCI numbers or N/A]"),
    ph(`[${EVIDENCE_TYPE_HINT}]`),
    ph("[Specific file names, report titles, or record types]"),
    ph("[Role who maintains evidence]"),
    ph("[Annual | Quarterly | Continuous]"),
    ph("[Notes]"),
    ph("[Catalog or assessment source]"),
    ph("[High | Medium | Low — your confidence this evidence is sufficient]"),
  ]);

  /** @type {DocSection[]} */
  const sections = [{ type: "table", heading: "Evidence Expectations", headers, rows }];

  return appendSourceMetadata(
    {
      title: "Evidence Expectation Matrix",
      description: "Reference matrix for expected evidence types.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @returns {TemplateDocument}
 */
function generateSTIGEvidenceChecklist(options) {
  const ph = placeholder(options);
  const headers = [
    "STIG Title",
    "STIG ID",
    "Rule ID",
    "Vuln ID",
    "Severity",
    "Title",
    "Check Text Summary",
    "Fix Text Summary",
    "CCI Refs",
    "Related Controls",
    "Evidence Expectation",
    "Validation Method",
    "N/A Justification",
    "Deviation Prompt",
    "Notes",
  ];

  const row = [
    ph("[STIG name]"),
    ph("[STIG ID]"),
    ph("[Rule ID]"),
    ph("[Vuln ID]"),
    ph("[High | Medium | Low]"),
    ph("[Rule title]"),
    ph("[Summarize what the check verifies]"),
    ph("[Summarize required fix or configuration]"),
    ph("[CCI reference numbers]"),
    ph("[Related NIST controls]"),
    ph("[What artifact proves compliance — scan, config, interview, etc.]"),
    ph("[How you validated — automated scan, manual review, interview]"),
    ph("[If not applicable, explain why this rule does not apply to your system]"),
    ph("[If deviating from the STIG, document approved exception and compensating control]"),
    ph("[Notes]"),
  ];

  /** @type {DocSection[]} */
  const sections = [{ type: "table", heading: "STIG Rules", headers, rows: [row] }];

  return appendSourceMetadata(
    {
      title: "STIG Evidence Checklist",
      description: "Blank checklist for STIG rule compliance evidence.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @param {any[]} controls
 * @returns {TemplateDocument}
 */
function generateInheritanceWorksheet(options, controls) {
  const ph = placeholder(options);
  const headers = [
    "Control ID",
    "Control Title",
    "Inheritance Type",
    "Common Control Provider",
    "Provider Responsibility",
    "Customer Responsibility",
    "Shared Notes",
    "Evidence Dependency",
    "Artifact Freshness Concern",
    "Local Delta Needed",
    "Source",
    "Notes",
  ];

  const rows = controls.map((c) => [
    c.id,
    c.title,
    ph("[Fully inherited | Hybrid | System-specific | Not inherited]"),
    ph("[Provider name — CSP, agency shared service, etc.]"),
    ph("[What the provider implements and attests to]"),
    ph("[What your program must still implement or verify locally]"),
    ph("[Shared responsibilities or coordination notes]"),
    ph("[Evidence you rely on from the provider — attestation, audit report, etc.]"),
    ph("[Is provider evidence current? Note review date or concern]"),
    ph("[Yes/No — does local implementation differ from provider baseline?]"),
    ph("[Source of inheritance decision — contract, FedRAMP package, etc.]"),
    ph("[Notes]"),
  ]);

  /** @type {DocSection[]} */
  const sections = [{ type: "table", heading: "Inheritance Plan", headers, rows }];

  return appendSourceMetadata(
    {
      title: "Inheritance Worksheet",
      description: "Worksheet to plan control inheritance.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @returns {TemplateDocument}
 */
function generateReciprocityChecklist(options) {
  const ph = placeholder(options);

  const headers = ["Item", "Status", "Reciprocity Guidance", "Notes"];
  const rows = [
    ["SSP (System Security Plan)", ph("[Not reviewed | In progress | Complete]"), "Verify the SSP matches the receiving agency's boundary and data types.", ph("[Notes]")],
    ["SAR (Security Assessment Report)", ph("[Not reviewed | In progress | Complete]"), "Confirm independent testing covers controls relevant to the new deployment.", ph("[Notes]")],
    ["POA&M (Plan of Action and Milestones)", ph("[Not reviewed | In progress | Complete]"), "Review open items, milestones, and whether remediation timelines are acceptable.", ph("[Notes]")],
    ["Boundary Comparison", ph("[Not reviewed | In progress | Complete]"), "Compare authorization boundaries — do data flows and components align?", ph("[Notes]")],
    ["Control Delta", ph("[Not reviewed | In progress | Complete]"), "List controls that differ between granting and receiving environments.", ph("[Notes]")],
    ["Risk Acceptance Review", ph("[Not reviewed | In progress | Complete]"), "Ensure all accepted risks were signed by the original Authorizing Official.", ph("[Notes]")],
    ["Artifact Freshness", ph("[Not reviewed | In progress | Complete]"), "Confirm artifacts are within your agency's review cadence (often under 1 year).", ph("[Notes]")],
  ];

  /** @type {DocSection[]} */
  const sections = [
    {
      type: "text",
      heading: "Granting Authorization Reference",
      content: ph("Package reference — Record the granting system's authorization ID, date, and AO name (placeholder only)."),
    },
    {
      type: "text",
      heading: "Receiving Organization",
      content: ph("Receiving org placeholder — Name the agency or program reusing this package. Do not pre-fill real org data."),
    },
    { type: "table", heading: "Body of Evidence Checklist", headers, rows },
    {
      type: "text",
      heading: "AO Decision Prompts",
      content: ph("Authorizing Official decision — What does the receiving AO need to decide? Note conditions, caveats, or additional testing required."),
    },
    {
      type: "text",
      heading: "Local Implementation Prompts",
      content: ph("Local gaps — What must the receiving program implement locally even if reciprocity is granted? List controls, evidence, or monitoring."),
    },
    {
      type: "text",
      heading: "Caveats",
      content: ph("Caveats and limitations — Document scope limits, expired artifacts, or conditions on reuse."),
    },
  ];

  return appendSourceMetadata(
    {
      title: "Reciprocity Checklist",
      description: "Checklist to review a package for reciprocity.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @returns {TemplateDocument}
 */
function generatePOAMStarter(options) {
  const ph = placeholder(options);
  const headers = [
    "Weakness ID",
    "Discovery Source",
    "Related Control",
    "Related STIG/SRG",
    "Weakness Description",
    "Risk Statement",
    "Severity",
    "Planned Remediation",
    "Milestone",
    "Completion Date",
    "Responsible Role",
    "Status",
    "Deviation Reference",
    "Risk Acceptance Reference",
    "Evidence Needed for Closure",
    "Notes",
  ];

  const row = [
    ph("[Weakness ID]"),
    ph("[Scan | Assessment | Audit | Incident — how was this found?]"),
    ph("[Control ID]"),
    ph("[STIG/SRG rule or N/A]"),
    ph("[Describe the weakness in plain language]"),
    ph("[What could go wrong if not fixed?]"),
    ph("[High | Medium | Low]"),
    ph("[Planned fix or compensating control]"),
    ph("[Next milestone or step]"),
    ph("[Target completion date]"),
    ph("[Role responsible]"),
    ph("[Open | In progress | Closed]"),
    ph("[Deviation or exception ID if applicable]"),
    ph("[Risk acceptance memo ID if risk is accepted]"),
    ph("[Evidence required before closing this item]"),
    ph("[Notes]"),
  ];

  /** @type {DocSection[]} */
  const sections = [{ type: "table", heading: "POA&M Items", headers, rows: [row] }];

  return appendSourceMetadata(
    {
      title: "POA&M Starter",
      description: "Blank Plan of Action and Milestones tracker.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @param {any[]} controls
 * @returns {TemplateDocument}
 */
function generateAssessmentPlanningWorksheet(options, controls) {
  const ph = placeholder(options);
  const headers = [
    "Control ID",
    "Control Title",
    "Assessment Method",
    "Assessor",
    "Target Date",
    "Status",
    "Observations",
  ];

  const rows = controls.map((c) => [
    c.id,
    c.title,
    ph("[Test | Interview | Examine | Automated — pick method(s)]"),
    ph("[Assessor name or role]"),
    ph("[Planned assessment date]"),
    ph("[Not started | Scheduled | Complete]"),
    ph("[Notes from planning — scope, sample size, tools]"),
  ]);

  /** @type {DocSection[]} */
  const sections = [{ type: "table", heading: "Assessment Plan", headers, rows }];

  return appendSourceMetadata(
    {
      title: "Assessment Planning Worksheet",
      description: "Worksheet to plan control assessments.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @returns {TemplateDocument}
 */
function generateConMonCalendar(options) {
  const ph = placeholder(options);
  const headers = [
    "Activity/Artifact",
    "Control Reference",
    "Frequency",
    "Source Basis Reference",
    "Next Review Date",
    "Responsible Role",
    "Status",
  ];

  const row = [
    ph("[Activity name — e.g., vulnerability scan, access review, config audit]"),
    ph("[Related control IDs]"),
    ph("[Annual | Quarterly | Monthly | Continuous]"),
    ph("[NIST SP 800-137 or agency ConMon policy reference]"),
    ph("[Next scheduled review date]"),
    ph("[Role responsible for this activity]"),
    ph("[Scheduled | Complete | Overdue]"),
  ];

  /** @type {DocSection[]} */
  const sections = [{ type: "table", heading: "Monitoring Schedule", headers, rows: [row] }];

  return appendSourceMetadata(
    {
      title: "Continuous Monitoring Calendar",
      description: "Calendar template for continuous monitoring activities.",
      sections,
    },
    options,
  );
}

function escapeCsv(val) {
  if (val == null) return '""';
  const str = String(val);
  if (str.includes(",") || str.includes('"') || str.includes("\n")) {
    return `"${str.replaceAll('"', '""')}"`;
  }
  return str;
}

function formatMarkdown(doc) {
  let out = `# ${doc.title}\n\n${doc.description}\n\n> **Disclaimer:** ${DISCLAIMER}\n\n`;
  for (const sec of doc.sections) {
    out += `## ${sec.heading}\n\n`;
    if (sec.type === "text") {
      out += `${sec.content}\n\n`;
    } else if (sec.type === "table") {
      out += `| ${sec.headers.join(" | ")} |\n`;
      out += `| ${sec.headers.map(() => "---").join(" | ")} |\n`;
      for (const row of sec.rows) {
        out += `| ${row.map((c) => String(c).replace(/\n/g, "<br>")).join(" | ")} |\n`;
      }
      out += "\n";
    }
  }
  return out;
}

function formatCsv(doc) {
  const table = doc.sections.find((s) => s.type === "table");
  let out = `# ${doc.title}\n# Disclaimer: ${DISCLAIMER.replace(/\n/g, " ")}\n`;
  if (table) {
    out += `${table.headers.map(escapeCsv).join(",")}\n`;
    for (const row of table.rows) {
      out += `${row.map(escapeCsv).join(",")}\n`;
    }
  } else {
    out += "Section,Content\n";
    for (const sec of doc.sections) {
      if (sec.type === "text") {
        out += `${escapeCsv(sec.heading)},${escapeCsv(sec.content)}\n`;
      }
    }
  }
  for (const sec of doc.sections) {
    if (sec.type === "text") {
      out += `# ${sec.heading}: ${String(sec.content).replace(/\n/g, " ")}\n`;
    }
  }
  return out;
}

function formatJson(doc) {
  const output = {
    title: doc.title,
    description: doc.description,
    disclaimer: DISCLAIMER,
    sections: doc.sections,
  };
  return JSON.stringify(output, null, 2);
}

function formatYaml(doc) {
  let out = `title: "${doc.title.replace(/"/g, '\\"')}"\n`;
  out += `description: "${doc.description.replace(/"/g, '\\"')}"\n`;
  out += `disclaimer: "${DISCLAIMER.replace(/"/g, '\\"')}"\n`;
  out += "sections:\n";
  for (const sec of doc.sections) {
    out += `  - heading: "${sec.heading.replace(/"/g, '\\"')}"\n`;
    out += `    type: ${sec.type}\n`;
    if (sec.type === "text") {
      out += `    content: "${sec.content.replace(/"/g, '\\"').replace(/\n/g, "\\n")}"\n`;
    } else if (sec.type === "table") {
      out += "    headers:\n";
      for (const h of sec.headers) {
        out += `      - "${h.replace(/"/g, '\\"')}"\n`;
      }
      out += "    rows:\n";
      for (const row of sec.rows) {
        out += `      - [${row.map((c) => `"${String(c).replace(/"/g, '\\"')}"`).join(", ")}]\n`;
      }
    }
  }
  return out;
}

/**
 * @param {any} options
 * @param {{ nodes?: any[], sources?: { sources?: any[] } }} dataset
 */
export function generateTemplate(options, dataset) {
  const normalized = {
    ...options,
    includeSourceFootnotes: true,
    includePlaceholders: options.includePlaceholders !== false,
    includeImplementationPrompts: options.includeImplementationPrompts !== false,
    includeEvidenceExpectations: options.includeEvidenceExpectations !== false,
    includeInheritancePrompts: options.includeInheritancePrompts !== false,
    includeReciprocityPrompts: options.includeReciprocityPrompts !== false,
    includeStigReferences: options.includeStigReferences !== false,
    environment: options.environment || "Generic",
    sourceRefs: options.sourceRefs || [],
    sources: options.sources || dataset?.sources || [],
  };

  let controls = [];
  if (normalized.framework) {
    controls = dataset.nodes
      .filter(
        (n) =>
          (n.node_type === "control" || n.node_type === "control_enhancement") &&
          n.metadata?.catalog_id === normalized.framework,
      )
      .map((n) => ({
        id: n.metadata?.item_id || n.id,
        title: n.metadata?.title || n.label || n.id,
        family: n.metadata?.control_family || "",
      }));
  }
  if (controls.length === 0) {
    controls = [{ id: "[Control ID]", title: "[Control Title]", family: "[Family]" }];
  }

  let doc;
  switch (normalized.templateType) {
    case "security_plan_starter":
      doc = generateSecurityPlanStarter(normalized, controls);
      break;
    case "implementation_statement_worksheet":
      doc = generateImplementationStatementWorksheet(normalized, controls);
      break;
    case "evidence_expectation_matrix":
      doc = generateEvidenceExpectationMatrix(normalized, controls);
      break;
    case "stig_evidence_checklist":
      doc = generateSTIGEvidenceChecklist(normalized);
      break;
    case "inheritance_worksheet":
      doc = generateInheritanceWorksheet(normalized, controls);
      break;
    case "reciprocity_checklist":
      doc = generateReciprocityChecklist(normalized);
      break;
    case "poam_starter":
      doc = generatePOAMStarter(normalized);
      break;
    case "assessment_planning_worksheet":
      doc = generateAssessmentPlanningWorksheet(normalized, controls);
      break;
    case "conmon_calendar":
      doc = generateConMonCalendar(normalized);
      break;
    default:
      doc = generateSecurityPlanStarter(normalized, controls);
  }

  let content;
  let extension;
  let mimeType;

  switch (normalized.format) {
    case "csv":
      content = formatCsv(doc);
      extension = "csv";
      mimeType = "text/csv";
      break;
    case "json":
      content = formatJson(doc);
      extension = "json";
      mimeType = "application/json";
      break;
    case "yaml":
      content = formatYaml(doc);
      extension = "yaml";
      mimeType = "text/yaml";
      break;
    case "markdown":
    default:
      content = formatMarkdown(doc);
      extension = "md";
      mimeType = "text/markdown";
      break;
  }

  const filename = `${normalized.templateType.replace(/_/g, "-")}-${new Date().toISOString().split("T")[0]}.${extension}`;
  return { content, filename, mimeType };
}
