/**
 * @typedef {Object} TextSection
 * @property {"text"} type
 * @property {string} heading
 * @property {string} content
 *
 * @typedef {Object} TableSection
 * @property {"table"} type
 * @property {string} heading
 * @property {string[]} headers
 * @property {any[][]} rows
 *
 * @typedef {TextSection | TableSection} DocSection
 *
 * @typedef {Object} TemplateDocument
 * @property {string} title
 * @property {string} description
 * @property {DocSection[]} sections
 */

import { PRODUCT_DISCLAIMER as DISCLAIMER } from '../shared/disclaimer.mjs';

const EVIDENCE_TYPE_HINT = "Policy | Procedure | Config screenshot | System report | Access review | Scan output | Interview | Architecture diagram | Change record | Training record | Incident record | Log sample | Inventory export | Exception memo";

/** @type {Record<string, { display_name: string, version: string }>} */
const SOURCE_FALLBACK = {
  "nist-oscal": { display_name: "SP 800-53 Rev. 5", version: "2026-06-09" },
  "disa-stig-library": { display_name: "DISA STIG Library", version: "2026-06-09" },
  "disa-cci-list": { display_name: "DISA CCI List", version: "2026-06-09" },
  "nist-800-37-rev2": { display_name: "NIST SP 800-37 Rev. 2", version: "2026-06-09" },
  "nist-sp-800-137": { display_name: "NIST SP 800-137", version: "2026-06-09" },
};

export const ENVIRONMENT_ARCHETYPES = [
  "Generic",
  "Cloud SaaS",
  "Platform service",
  "Enclave",
  "On-premises",
  "Hybrid",
  "Enterprise service",
];

/**
 * @param {any} options
 * @returns {(txt: string) => string}
 */
function placeholder(options) {
  return (txt) => (options.includePlaceholders !== false ? txt : "");
}

/**
 * Truncate a plain-language summary at a word boundary so it fits a table
 * cell without mid-word cuts.
 *
 * @param {string} text
 * @param {number} [max]
 * @returns {string}
 */
function truncatePlain(text, max = 170) {
  const str = String(text || "").trim();
  if (str.length <= max) return str;
  const cut = str.slice(0, max);
  const lastSpace = cut.lastIndexOf(" ");
  const clipped = (lastSpace > 0 ? cut.slice(0, lastSpace) : cut).replace(/[\s,;:.]+$/, "");
  return `${clipped}…`;
}

/**
 * @param {(string | { id: string })[]} sourceRefs
 * @param {any[]} sources
 * @returns {string[]}
 */
function resolveSourceLines(sourceRefs, sources) {
  const sourceMap = new Map((sources || []).map((s) => [s.id, s]));
  const lines = [];
  for (const ref of sourceRefs || []) {
    const id = typeof ref === "string" ? ref : ref.id;
    const src = sourceMap.get(id) || SOURCE_FALLBACK[id];
    if (src) {
      const name = src.display_name || src.name || id;
      const version = src.version || "unknown";
      lines.push(`${name} (version ${version})`);
    } else if (id) {
      lines.push(id);
    }
  }
  return lines;
}

/**
 * @param {any} options
 * @returns {string}
 */
export function buildSourceMetadata(options) {
  const lines = [];
  if (options.framework) {
    lines.push(`Framework context: ${options.framework}`);
  }
  lines.push(`Environment archetype: ${options.environment || "Generic"}`);
  const refLines = resolveSourceLines(options.sourceRefs, options.sources);
  if (refLines.length) {
    lines.push("Reference sources:");
    for (const line of refLines) {
      lines.push(`- ${line}`);
    }
  }
  lines.push("Generated by Control Atlas (reference aid only).");
  return lines.join("\n");
}

/**
 * @param {TemplateDocument} doc
 * @param {any} options
 * @returns {TemplateDocument}
 */
function appendSourceMetadata(doc, options) {
  doc.sections.push({
    type: "text",
    heading: "Source Metadata",
    content: buildSourceMetadata(options),
  });
  return doc;
}

/**
 * @param {any} options
 * @param {any[]} controls
 * @param {ReturnType<typeof buildControlCrossRefIndex> | null} [crossRef]
 * @returns {TemplateDocument}
 */
function generateSecurityPlanStarter(options, controls, crossRef) {
  const ph = placeholder(options);
  const env = options.environment || "Generic";

  const baselineHeaders = ["Control ID", "Control Title", "What It Means", "Implementation Statement", "Evidence", "Status"];
  const baselineRows = controls.map((c) => [
    c.id,
    c.title,
    truncatePlain(c.plain),
    ph("[How is this implemented for this system?]"),
    ph("[Artifact name(s)]"),
    ph("[Planned | Implemented | Inherited | N/A]"),
  ]);

  // One-time fill guidance, stated once instead of repeated per control row.
  const guidanceBullets = [];
  if (options.includeImplementationPrompts !== false) {
    guidanceBullets.push(`- Implementation Statement: describe how each control is implemented in the ${env} environment — the policies, technical mechanisms, and who maintains them.`);
  }
  if (options.includeEvidenceExpectations !== false) {
    guidanceBullets.push("- Evidence: name the artifact(s) that would show the control is working — reports, configs, records — and how often they are reviewed.");
  }
  if (options.includeInheritancePrompts !== false) {
    guidanceBullets.push("- Inherited controls: mark Status as Inherited, then record the provider and your remaining local responsibility in the Inheritance Summary below.");
  }
  if (options.includeReciprocityPrompts !== false) {
    guidanceBullets.push("- Reciprocity: note in the Implementation Statement whether assessment results can be reused at another agency, plus any gaps or caveats.");
  }

  // Blank starter rows: practitioners list the handful of inherited services,
  // not every control in the baseline.
  const inheritanceHeaders = ["Control ID", "Inheritance Type", "Provider", "Customer Responsibility", "Notes"];
  const inheritanceRows = Array.from({ length: 10 }, () => [
    ph("[Control ID]"),
    ph("[Fully inherited | Hybrid | Not inherited]"),
    ph("[Provider name]"),
    ph("[What your team still implements locally]"),
    ph("[Notes]"),
  ]);

  // Real cross-referenced STIG/SRG rule IDs only — no placeholder rows.
  const stigRows = [];
  if (options.includeStigReferences !== false && crossRef) {
    for (const c of controls) {
      if (!c.nodeId) continue;
      const refs = crossRefForControl(crossRef, c.nodeId);
      if (refs.stigIds.length) stigRows.push([c.id, refs.stigIds.join("; ")]);
    }
  }

  /** @type {DocSection[]} */
  const sections = [
    {
      type: "text",
      heading: "Title Page",
      content: ph("System name and short title — What system is this plan for? Write a name and one-line description a reviewer can use to understand scope."),
    },
    {
      type: "text",
      heading: "Document Metadata",
      content: ph("Version, date, author role, and classification — Who owns this document and when was it last updated? Use your agency's labeling rules."),
    },
    {
      type: "text",
      heading: "System Overview",
      content: ph("System purpose and mission support — What does this system do and why does it exist? Avoid jargon; explain who uses it and for what."),
    },
    {
      type: "text",
      heading: "Authorization Boundary",
      content: ph("Boundary description — What is inside the authorization boundary? List major components, data flows, and what is explicitly out of scope."),
    },
    {
      type: "text",
      heading: "System Environment",
      content: `Environment archetype: ${env}. Describe hosting, deployment model, and shared services that affect control implementation.`,
    },
    {
      type: "text",
      heading: "Data Types",
      content: ph("Data handled — What types of data does the system process or store? Note sensitivity levels (e.g., CUI, PII) and retention expectations."),
    },
    {
      type: "text",
      heading: "User Roles",
      content: ph("Roles and privileges — Who uses the system (admin, operator, end user)? Describe access levels and separation of duties."),
    },
    {
      type: "text",
      heading: "Interconnections",
      content: ph("External connections — What other systems connect to this one? Note direction of data flow and security agreements."),
    },
    ...(guidanceBullets.length
      ? [
          /** @type {DocSection} */ ({
            type: "text",
            heading: "How to Fill the Control Baseline",
            content: guidanceBullets.join("\n"),
          }),
        ]
      : []),
    { type: "table", heading: "Control Baseline", headers: baselineHeaders, rows: baselineRows },
    { type: "table", heading: "Inheritance Summary", headers: inheritanceHeaders, rows: inheritanceRows },
    {
      type: "text",
      heading: "Evidence Expectations",
      content: "Plan evidence in the dedicated Evidence Expectation Matrix template — it lists every control with its related CCIs and STIG/SRG rules and gives you a column to name the artifact you will collect.",
    },
    ...(stigRows.length
      ? [
          /** @type {DocSection} */ ({
            type: "table",
            heading: "STIG/SRG References",
            headers: ["Control ID", "STIG/SRG rule IDs"],
            rows: stigRows,
          }),
        ]
      : []),
    {
      type: "text",
      heading: "Revision History",
      content: ph("Version | Date | Author role | Summary of changes — Track updates so reviewers know what changed since the last review."),
    },
  ];

  return appendSourceMetadata(
    {
      title: "System Security Plan (SSP) Starter",
      description: "Blank planning structure for a system security plan.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @param {any[]} controls
 * @returns {TemplateDocument}
 */
function generateImplementationStatementWorksheet(options, controls) {
  const ph = placeholder(options);
  const headers = [
    "Control ID",
    "Control Title",
    "What It Means",
    "Implementation Statement",
    "Responsible Role",
    "Status",
  ];

  const rows = controls.map((c) => [
    c.id,
    c.title,
    truncatePlain(c.plain),
    ph("[Draft statement — describe how this control is implemented]"),
    ph("[Role responsible for maintaining this control]"),
    ph("[Draft | Reviewed | Approved]"),
  ]);

  /** @type {DocSection[]} */
  const sections = [
    {
      type: "text",
      heading: "How to Draft a Statement",
      content: `For each control, describe the technical controls, policies, or mechanisms that implement it. Include who operates them and how often they are reviewed. Typical evidence types you can point to: ${EVIDENCE_TYPE_HINT}.`,
    },
    { type: "table", heading: "Implementation Statements", headers, rows },
  ];

  return appendSourceMetadata(
    {
      title: "Control Implementation Statement Worksheet",
      description: "Worksheet to draft control implementation statements.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @param {any[]} controls
 * @param {ReturnType<typeof buildControlCrossRefIndex> | null} [crossRef]
 * @returns {TemplateDocument}
 */
function generateEvidenceExpectationMatrix(options, controls, crossRef) {
  const ph = placeholder(options);
  const headers = [
    "Control ID",
    "Control Title",
    "What It Means",
    "Related CCIs",
    "Related STIG/SRG",
    "Evidence to Collect",
  ];

  const rows = controls.map((c) => {
    const refs = crossRef && c.nodeId ? crossRefForControl(crossRef, c.nodeId) : null;
    return [
      c.id,
      c.title,
      truncatePlain(c.plain),
      refs && refs.cciIds.length ? refs.cciIds.join("; ") : "—",
      refs && refs.stigIds.length ? refs.stigIds.join("; ") : "—",
      ph("[Artifact type + name]"),
    ];
  });

  /** @type {DocSection[]} */
  const sections = [
    {
      type: "text",
      heading: "How to Use This Matrix",
      content: [
        `- Evidence types to pick from: ${EVIDENCE_TYPE_HINT}.`,
        "- Name each artifact specifically (file name, report title, or record type) — \"screenshots\" is not an artifact.",
        "- Assign an owner role (not a person) who maintains each artifact.",
        "- Set a review cadence — Annual, Quarterly, or Continuous — so evidence stays fresh.",
        "- Rate your confidence (High | Medium | Low) that the evidence would satisfy an assessor, and revisit Low items first.",
      ].join("\n"),
    },
    { type: "table", heading: "Evidence Expectations", headers, rows },
  ];

  return appendSourceMetadata(
    {
      title: "Evidence Expectation Matrix",
      description: "Reference matrix for expected evidence types.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @returns {TemplateDocument}
 */
function generateSTIGEvidenceChecklist(options) {
  const headers = [
    "Rule ID",
    "Severity",
    "Rule Title",
    "Evidence",
    "Validation Method",
    "Notes",
  ];
  const rows = Array.from({ length: 10 }, () => ["", "", "", "", "", ""]);

  /** @type {DocSection[]} */
  const sections = [
    {
      type: "text",
      heading: "Field Guide",
      content: [
        "- **STIG Title / STIG ID** — the benchmark this rule comes from; record it once per checklist, not per row.",
        "- **Rule ID / Vuln ID** — the identifiers from the STIG (SV-… / V-…); the Rule ID goes in the tracker.",
        "- **Severity** — CAT I (high), CAT II (medium), or CAT III (low) as assigned by the STIG.",
        "- **Rule Title** — the rule's short name from the benchmark.",
        "- **Check / Fix text** — what the check verifies and the required configuration; summarize in Notes if a rule needs context.",
        "- **CCI Refs / Related Controls** — the CCIs the rule references and the NIST controls they map to.",
        "- **Evidence** — the artifact that proves compliance: scan output, configuration export, interview record.",
        "- **Validation Method** — how you validated: automated scan, manual review, or interview.",
        "- **N/A Justification** — if a rule does not apply, record why in Notes.",
        "- **Deviation** — if deviating from the STIG, record the approved exception and compensating control in Notes.",
      ].join("\n"),
    },
    { type: "table", heading: "STIG Rule Tracker", headers, rows },
  ];

  return appendSourceMetadata(
    {
      title: "STIG Evidence Checklist",
      description: "Blank checklist for STIG rule compliance evidence.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @param {any[]} controls
 * @returns {TemplateDocument}
 */
function generateInheritanceWorksheet(options, controls) {
  const ph = placeholder(options);
  const headers = [
    "Control ID",
    "Control Title",
    "What It Means",
    "Inherited?",
    "Provider",
    "Customer Responsibility",
  ];

  const rows = controls.map((c) => [
    c.id,
    c.title,
    truncatePlain(c.plain),
    ph("[Fully inherited | Hybrid | System-specific | Not inherited]"),
    ph("[Provider name — CSP, agency shared service, etc.]"),
    ph("[What your program must still implement or verify locally]"),
  ]);

  /** @type {DocSection[]} */
  const sections = [
    {
      type: "text",
      heading: "How to Plan Inheritance",
      content: [
        "- For each inherited or hybrid control, name the evidence you rely on from the provider — attestation, audit report, FedRAMP package.",
        "- Check that provider evidence is current; note the review date or any freshness concern.",
        "- Record whether your local implementation differs from the provider baseline (a local delta means extra work and extra evidence).",
        "- Cite the source of the inheritance decision — contract, FedRAMP package, or agency agreement.",
      ].join("\n"),
    },
    { type: "table", heading: "Inheritance Plan", headers, rows },
  ];

  return appendSourceMetadata(
    {
      title: "Inheritance Worksheet",
      description: "Worksheet to plan control inheritance.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @returns {TemplateDocument}
 */
function generateReciprocityChecklist(options) {
  const ph = placeholder(options);

  const headers = ["Item", "Status", "Reciprocity Guidance", "Notes"];
  const rows = [
    ["SSP (System Security Plan)", ph("[Not reviewed | In progress | Complete]"), "Verify the SSP matches the receiving agency's boundary and data types.", ph("[Notes]")],
    ["SAR (Security Assessment Report)", ph("[Not reviewed | In progress | Complete]"), "Confirm independent testing covers controls relevant to the new deployment.", ph("[Notes]")],
    ["POA&M (Plan of Action and Milestones)", ph("[Not reviewed | In progress | Complete]"), "Review open items, milestones, and whether remediation timelines are acceptable.", ph("[Notes]")],
    ["Boundary Comparison", ph("[Not reviewed | In progress | Complete]"), "Compare authorization boundaries — do data flows and components align?", ph("[Notes]")],
    ["Control Delta", ph("[Not reviewed | In progress | Complete]"), "List controls that differ between granting and receiving environments.", ph("[Notes]")],
    ["Risk Acceptance Review", ph("[Not reviewed | In progress | Complete]"), "Ensure all accepted risks were signed by the original Authorizing Official.", ph("[Notes]")],
    ["Artifact Freshness", ph("[Not reviewed | In progress | Complete]"), "Confirm artifacts are within your agency's review cadence (often under 1 year).", ph("[Notes]")],
  ];

  /** @type {DocSection[]} */
  const sections = [
    {
      type: "text",
      heading: "Granting Authorization Reference",
      content: ph("Package reference — Record the granting system's authorization ID, date, and AO name (placeholder only)."),
    },
    {
      type: "text",
      heading: "Receiving Organization",
      content: ph("Receiving org placeholder — Name the agency or program reusing this package. Do not pre-fill real org data."),
    },
    { type: "table", heading: "Body of Evidence Checklist", headers, rows },
    {
      type: "text",
      heading: "AO Decision Prompts",
      content: ph("Authorizing Official decision — What does the receiving AO need to decide? Note conditions, caveats, or additional testing required."),
    },
    {
      type: "text",
      heading: "Local Implementation Prompts",
      content: ph("Local gaps — What must the receiving program implement locally even if reciprocity is granted? List controls, evidence, or monitoring."),
    },
    {
      type: "text",
      heading: "Caveats",
      content: ph("Caveats and limitations — Document scope limits, expired artifacts, or conditions on reuse."),
    },
  ];

  return appendSourceMetadata(
    {
      title: "Reciprocity Checklist",
      description: "Checklist to review a package for reciprocity.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @returns {TemplateDocument}
 */
function generatePOAMStarter(options) {
  // Field set aligns with the eMASS and FedRAMP POA&M presets so an export can
  // be mapped into either workflow: severity category (CAT I/II/III), original
  // detection date, resources required, and a named point of contact sit
  // alongside the core weakness/remediation fields. The full field guide is a
  // text section; the tracker table keeps the six columns you fill first.
  const fieldGuide = [
    ["POA&M ID", "unique tracking number for this item"],
    ["Detection Source", "Scan | Assessment | Audit | Incident — how was this found?"],
    ["Related Control (CCI)", "control ID and/or CCI number"],
    ["Related STIG/SRG", "STIG/SRG rule or N/A"],
    ["Weakness Description", "describe the weakness in plain language"],
    ["Risk Statement", "what could go wrong if not fixed?"],
    ["Severity", "High | Medium | Low"],
    ["Severity Category (CAT)", "CAT I = high | CAT II = medium | CAT III = low"],
    ["Point of Contact (POC)", "name/role accountable for remediation"],
    ["Resources Required", "funding, staff, or tools needed to remediate"],
    ["Planned Remediation", "planned fix or compensating control"],
    ["Milestones with Completion Dates", "milestone description | target date; one per line"],
    ["Original Detection Date", "date the weakness was first identified"],
    ["Scheduled Completion Date", "target completion date"],
    ["Responsible Office/Role", "responsible office or role"],
    ["Status", "Open | Ongoing | Risk Accepted | Completed"],
    ["Deviation Reference", "deviation or exception ID if applicable"],
    ["Risk Acceptance Reference", "risk acceptance memo ID if risk is accepted"],
    ["Evidence Needed for Closure", "evidence required before closing this item"],
    ["Notes", "anything a reviewer needs that does not fit above"],
  ];

  const trackerHeaders = [
    "POA&M ID",
    "Weakness",
    "Related Control/CCI",
    "Severity",
    "Scheduled Completion",
    "Status",
  ];
  const trackerRows = Array.from({ length: 10 }, () => ["", "", "", "", "", ""]);

  /** @type {DocSection[]} */
  const sections = [
    {
      type: "text",
      heading: "POA&M Field Guide",
      content: fieldGuide.map(([name, hint]) => `- **${name}** — ${hint}`).join("\n"),
    },
    { type: "table", heading: "POA&M Tracker", headers: trackerHeaders, rows: trackerRows },
  ];

  return appendSourceMetadata(
    {
      title: "POA&M Starter",
      description: "Blank Plan of Action and Milestones tracker.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @param {any[]} controls
 * @returns {TemplateDocument}
 */
function generateAssessmentPlanningWorksheet(options, controls) {
  const ph = placeholder(options);
  const headers = [
    "Control ID",
    "Control Title",
    "What It Means",
    "Assessment Method",
    "Evidence to Request",
    "Notes",
  ];

  const rows = controls.map((c) => [
    c.id,
    c.title,
    truncatePlain(c.plain),
    ph("[Examine | Interview | Test]"),
    ph("[Artifacts to request before the assessment]"),
    ph("[Notes]"),
  ]);

  /** @type {DocSection[]} */
  const sections = [
    {
      type: "text",
      heading: "How to Plan an Assessment",
      content: [
        "- Pick one or more methods per control: Examine (review artifacts), Interview (talk to the people who run it), Test (exercise the mechanism).",
        "- Request evidence before the assessment window so gaps surface early.",
        "- Track assessor, target date, and completion status in your schedule; use Notes for scope, sample size, and tooling.",
      ].join("\n"),
    },
    { type: "table", heading: "Assessment Plan", headers, rows },
  ];

  return appendSourceMetadata(
    {
      title: "Assessment Planning Worksheet",
      description: "Worksheet to plan control assessments.",
      sections,
    },
    options,
  );
}

/**
 * @param {any} options
 * @returns {TemplateDocument}
 */
function generateConMonCalendar(options) {
  const ph = placeholder(options);
  const headers = [
    "Activity",
    "Control Refs",
    "Frequency",
    "Owner",
    "Next Review",
    "Status",
  ];

  // Canonical continuous-monitoring activities (NIST SP 800-137 aligned) with
  // typical cadences — a real starter schedule, not a placeholder row. Adjust
  // frequencies to your agency's ConMon strategy.
  const starterActivities = [
    ["Vulnerability scanning", "RA-5", "Monthly"],
    ["Access review", "AC-2", "Quarterly"],
    ["Configuration audit", "CM-6", "Quarterly"],
    ["Audit log review", "AU-6", "Weekly"],
    ["Contingency plan test", "CP-4", "Annual"],
    ["Security awareness training", "AT-2", "Annual"],
    ["POA&M review", "CA-5", "Monthly"],
    ["Penetration test", "CA-8", "Annual"],
    ["Incident response exercise", "IR-3", "Annual"],
    ["Inventory reconciliation", "CM-8", "Quarterly"],
  ];
  const rows = starterActivities.map(([activity, refs, frequency]) => [
    activity,
    refs,
    frequency,
    ph("[Role]"),
    ph("[Date]"),
    "",
  ]);

  /** @type {DocSection[]} */
  const sections = [{ type: "table", heading: "Monitoring Schedule", headers, rows }];

  return appendSourceMetadata(
    {
      title: "Continuous Monitoring Calendar",
      description: "Calendar template for continuous monitoring activities.",
      sections,
    },
    options,
  );
}

function escapeCsv(val) {
  if (val == null) return '""';
  const str = String(val);
  if (str.includes(",") || str.includes('"') || str.includes("\n")) {
    return `"${str.replaceAll('"', '""')}"`;
  }
  return str;
}

// Markdown layout limits: pipe tables wider than ~6 columns are unreadable in
// any renderer, so wide sections are restructured (constant guidance columns
// become prose, varying columns are split across narrow keyed tables).
const MD_MAX_TABLE_COLUMNS = 6;
const MD_LONG_CELL_THRESHOLD = 80;
const MD_LONG_CHUNK_COLUMNS = 4;

/** Escape a value for use inside a markdown pipe-table cell. */
function mdCell(value) {
  return String(value ?? "").replace(/\|/g, "\\|").replace(/\n/g, "<br>");
}

/** Flatten a value to a single prose line. */
function mdProse(value) {
  return String(value ?? "").replace(/\n/g, " ").trim();
}

function mdTableBlock(headers, rows) {
  let out = `| ${headers.map(mdCell).join(" | ")} |\n`;
  out += `| ${headers.map(() => "---").join(" | ")} |\n`;
  for (const row of rows) {
    out += `| ${row.map(mdCell).join(" | ")} |\n`;
  }
  return `${out}\n`;
}

/**
 * Render a table section as markdown. Narrow tables pass through as one pipe
 * table. Wide tables (> {@link MD_MAX_TABLE_COLUMNS} columns) are
 * restructured for readability, deterministically:
 * - single-row starters (e.g. the 20-column POA&M) become a labelled field
 *   list — prose, no table;
 * - multi-row tables emit columns whose value is identical on every row
 *   (guidance/placeholder columns) as prose bullets above the tables, then
 *   split the varying columns into keyed tables of at most
 *   {@link MD_MAX_TABLE_COLUMNS} columns: identity/status columns first, then
 *   long prompt/detail columns in narrower chunks, each table repeating the
 *   first (key) column so rows stay correlated.
 */
function formatMarkdownTableSection(sec) {
  const headers = sec.headers || [];
  const rows = (sec.rows || []).map((r) => r || []);
  if (headers.length <= MD_MAX_TABLE_COLUMNS) {
    return mdTableBlock(headers, rows);
  }

  if (rows.length <= 1) {
    const row = rows[0] || [];
    let out = "";
    headers.forEach((h, i) => {
      out += `- **${mdProse(h)}:** ${mdProse(row[i])}\n`;
    });
    return `${out}\n`;
  }

  const constantIdx = [];
  const shortIdx = [];
  const longIdx = [];
  for (let i = 1; i < headers.length; i++) {
    const first = String(rows[0][i] ?? "");
    if (rows.every((r) => String(r[i] ?? "") === first)) {
      constantIdx.push(i);
      continue;
    }
    const maxLen = rows.reduce(
      (max, r) => Math.max(max, String(r[i] ?? "").length),
      String(headers[i] ?? "").length,
    );
    (maxLen > MD_LONG_CELL_THRESHOLD ? longIdx : shortIdx).push(i);
  }

  let out = "";
  for (const i of constantIdx) {
    out += `- **${mdProse(headers[i])}:** ${mdProse(rows[0][i])}\n`;
  }
  if (constantIdx.length > 0) out += "\n";

  const emitChunks = (indices, maxColumns) => {
    for (let start = 0; start < indices.length; start += maxColumns - 1) {
      const cols = [0, ...indices.slice(start, start + maxColumns - 1)];
      out += mdTableBlock(
        cols.map((i) => headers[i]),
        rows.map((r) => cols.map((i) => r[i])),
      );
    }
  };
  emitChunks(shortIdx, MD_MAX_TABLE_COLUMNS);
  emitChunks(longIdx, MD_LONG_CHUNK_COLUMNS);
  if (shortIdx.length === 0 && longIdx.length === 0) {
    // Everything but the key column was constant: still emit the key column.
    out += mdTableBlock([headers[0]], rows.map((r) => [r[0]]));
  }
  return out;
}

function formatMarkdown(doc) {
  let out = `# ${doc.title}\n\n${doc.description}\n\n> **Disclaimer:** ${DISCLAIMER}\n\n`;
  for (const sec of doc.sections) {
    out += `## ${sec.heading}\n\n`;
    if (sec.type === "text") {
      out += `${sec.content}\n\n`;
    } else if (sec.type === "table") {
      out += formatMarkdownTableSection(sec);
    }
  }
  return out;
}

function formatCsv(doc) {
  const table = doc.sections.find((s) => s.type === "table");
  // Data first: column headers land on row 1 so the export imports cleanly into
  // a spreadsheet without a manual header-row fix. Title, disclaimer, and the
  // text/metadata sections follow as `#`-prefixed footer comment lines.
  let out = "";
  if (table) {
    out += `${table.headers.map(escapeCsv).join(",")}\n`;
    for (const row of table.rows) {
      out += `${row.map(escapeCsv).join(",")}\n`;
    }
  } else {
    out += "Section,Content\n";
    for (const sec of doc.sections) {
      if (sec.type === "text") {
        out += `${escapeCsv(sec.heading)},${escapeCsv(sec.content)}\n`;
      }
    }
  }
  out += `# ${doc.title}\n`;
  out += `# Disclaimer: ${DISCLAIMER.replace(/\n/g, " ")}\n`;
  for (const sec of doc.sections) {
    if (sec.type === "text") {
      out += `# ${sec.heading}: ${String(sec.content).replace(/\n/g, " ")}\n`;
    }
  }
  return out;
}

function formatJson(doc) {
  const output = {
    title: doc.title,
    description: doc.description,
    disclaimer: DISCLAIMER,
    sections: doc.sections,
  };
  return JSON.stringify(output, null, 2);
}

function formatYaml(doc) {
  let out = `title: "${doc.title.replace(/"/g, '\\"')}"\n`;
  out += `description: "${doc.description.replace(/"/g, '\\"')}"\n`;
  out += `disclaimer: "${DISCLAIMER.replace(/"/g, '\\"')}"\n`;
  out += "sections:\n";
  for (const sec of doc.sections) {
    out += `  - heading: "${sec.heading.replace(/"/g, '\\"')}"\n`;
    out += `    type: ${sec.type}\n`;
    if (sec.type === "text") {
      out += `    content: "${sec.content.replace(/"/g, '\\"').replace(/\n/g, "\\n")}"\n`;
    } else if (sec.type === "table") {
      out += "    headers:\n";
      for (const h of sec.headers) {
        out += `      - "${h.replace(/"/g, '\\"')}"\n`;
      }
      out += "    rows:\n";
      for (const row of sec.rows) {
        out += `      - [${row.map((c) => `"${String(c).replace(/"/g, '\\"')}"`).join(", ")}]\n`;
      }
    }
  }
  return out;
}

/**
 * Central control-collection path shared by ALL templates. Filters to
 * control/control_enhancement nodes for the requested catalog and excludes
 * withdrawn controls (SP 800-53 lifecycle_status: 'withdrawn') so retired
 * control IDs (AC-13, SA-12, SA-13, ...) never appear in generated artifacts.
 *
 * @param {any[]} nodes
 * @param {string} catalogId
 * @returns {any[]}
 */
function collectCatalogControls(nodes, catalogId) {
  return (nodes || []).filter(
    (n) =>
      (n.node_type === "control" || n.node_type === "control_enhancement") &&
      n.metadata?.catalog_id === catalogId &&
      n.lifecycle_status !== "withdrawn",
  );
}

/**
 * When a selected framework catalog has no control/control_enhancement nodes
 * of its own (e.g. FedRAMP Rev. 5, whose catalog only carries `baseline`
 * nodes), resolve the member NIST 800-53 controls via the catalog's
 * baseline-membership edges instead of emitting a placeholder row.
 *
 * Edge shape observed in data/generated/edges.json: baseline nodes are
 * `${catalogId}:${baselineItemId}` (e.g. "fedramp-rev5:LOW"); each has an
 * `includes` edge with `source_node_id` = the baseline node and
 * `target_node_id` = the member `nist-800-53:<CONTROL_ID>` control node.
 * Membership is unioned across every baseline node in the catalog.
 *
 * @param {any} dataset
 * @param {string} catalogId
 * @returns {any[]}
 */
function resolveControlsViaBaselineEdges(dataset, catalogId) {
  const nodes = dataset?.nodes || [];
  const edges = dataset?.edges || [];
  const nodeById = new Map(nodes.map((n) => [n.id, n]));

  const baselineNodeIds = new Set(
    nodes
      .filter((n) => n.node_type === "baseline" && n.metadata?.catalog_id === catalogId)
      .map((n) => n.id),
  );
  if (baselineNodeIds.size === 0) return [];

  const memberNodeIds = new Set();
  for (const edge of edges) {
    if (edge.relationship_type !== "includes") continue;
    if (baselineNodeIds.has(edge.source_node_id)) {
      memberNodeIds.add(edge.target_node_id);
    } else if (baselineNodeIds.has(edge.target_node_id)) {
      memberNodeIds.add(edge.source_node_id);
    }
  }

  const memberControls = [...memberNodeIds]
    .map((id) => nodeById.get(id))
    .filter(
      (n) =>
        n &&
        (n.node_type === "control" || n.node_type === "control_enhancement") &&
        n.lifecycle_status !== "withdrawn",
    );

  memberControls.sort((a, b) => {
    const aId = a.metadata?.item_id || a.id;
    const bId = b.metadata?.item_id || b.id;
    return aId.localeCompare(bId, undefined, { numeric: true, sensitivity: "base" });
  });

  return memberControls;
}

/**
 * Build a control → CCI → STIG/SRG cross-reference index from the graph edges.
 *
 * The bridge is the DISA CCI list (STIG scope memory): a NIST 800-53 control
 * `maps_to` one or more `disa-cci:*` requirement nodes, and each STIG rule /
 * SRG requirement `references` the CCIs it satisfies. Walking control → CCI →
 * STIG lets a template cite the real rule IDs and CCI numbers instead of
 * leaving placeholder cells.
 *
 * @param {{ nodes?: any[], edges?: any[] }} dataset
 * @returns {{ controlToCci: Map<string, Set<string>>, cciToStig: Map<string, Set<string>>, byId: Map<string, any> }}
 */
function buildControlCrossRefIndex(dataset) {
  const nodes = dataset?.nodes || [];
  const edges = dataset?.edges || [];
  const byId = new Map(nodes.map((n) => [n.id, n]));
  const isCci = (id) => typeof id === "string" && id.startsWith("disa-cci:");
  const isStigNode = (n) =>
    n && (n.node_type === "stig_rule" || n.node_type === "srg_requirement");

  /** @type {Map<string, Set<string>>} */
  const controlToCci = new Map();
  /** @type {Map<string, Set<string>>} */
  const cciToStig = new Map();

  for (const edge of edges) {
    if (edge.relationship_type === "maps_to") {
      const { source_node_id: s, target_node_id: t } = edge;
      let cci;
      let ctrl;
      if (isCci(s)) {
        cci = s;
        ctrl = t;
      } else if (isCci(t)) {
        cci = t;
        ctrl = s;
      }
      if (cci && ctrl) {
        if (!controlToCci.has(ctrl)) controlToCci.set(ctrl, new Set());
        controlToCci.get(ctrl).add(cci);
      }
    } else if (edge.relationship_type === "references") {
      const { source_node_id: s, target_node_id: t } = edge;
      let cci;
      let stig;
      if (isCci(s) && isStigNode(byId.get(t))) {
        cci = s;
        stig = t;
      } else if (isCci(t) && isStigNode(byId.get(s))) {
        cci = t;
        stig = s;
      }
      if (cci && stig) {
        if (!cciToStig.has(cci)) cciToStig.set(cci, new Set());
        cciToStig.get(cci).add(stig);
      }
    }
  }

  return { controlToCci, cciToStig, byId };
}

/**
 * Resolve the real CCI numbers and STIG/SRG rule IDs cross-referenced by a
 * control node, using the index from {@link buildControlCrossRefIndex}.
 *
 * @param {ReturnType<typeof buildControlCrossRefIndex>} index
 * @param {string} controlNodeId
 * @returns {{ cciIds: string[], stigIds: string[] }}
 */
function crossRefForControl(index, controlNodeId) {
  const idOf = (nodeId) => index.byId.get(nodeId)?.metadata?.item_id || nodeId;
  const cciNodeIds = [...(index.controlToCci.get(controlNodeId) || [])];
  const stigNodeIds = new Set();
  for (const cci of cciNodeIds) {
    for (const stig of index.cciToStig.get(cci) || []) stigNodeIds.add(stig);
  }
  const sortIds = (arr) =>
    arr.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" }));
  return {
    cciIds: sortIds(cciNodeIds.map(idOf)),
    stigIds: sortIds([...stigNodeIds].map(idOf)),
  };
}

/**
 * Collect the control node IDs that belong to a named baseline (Low / Moderate
 * / High / Privacy / LI-SaaS). Baseline membership lives in `baseline` nodes
 * (e.g. `nist-800-53b:LOW`, `fedramp-rev5:MODERATE`) linked to their member
 * controls with `includes` edges. Baseline nodes are matched by item_id,
 * preferring the catalog that fits the selected framework so a NIST 800-53
 * template scopes to 800-53B membership rather than FedRAMP's.
 *
 * @param {{ nodes?: any[], edges?: any[] }} dataset
 * @param {string} baselineItemId
 * @param {string} frameworkCatalogId
 * @returns {Set<string>}
 */
function collectBaselineMemberIds(dataset, baselineItemId, frameworkCatalogId) {
  const nodes = dataset?.nodes || [];
  const edges = dataset?.edges || [];
  const target = String(baselineItemId).toUpperCase();

  const baselineNodes = nodes.filter(
    (n) =>
      n.node_type === "baseline" &&
      String(n.metadata?.item_id || "").toUpperCase() === target,
  );
  if (baselineNodes.length === 0) return new Set();

  // Prefer baseline nodes from the framework's own catalog; otherwise fall back
  // to the canonical NIST SP 800-53B baselines.
  const sameCatalog = baselineNodes.filter(
    (n) => n.metadata?.catalog_id === frameworkCatalogId,
  );
  const nist80053b = baselineNodes.filter(
    (n) => n.metadata?.catalog_id === "nist-800-53b",
  );
  const scoped =
    sameCatalog.length > 0 ? sameCatalog : nist80053b.length > 0 ? nist80053b : baselineNodes;
  const baselineNodeIds = new Set(scoped.map((n) => n.id));

  const members = new Set();
  for (const edge of edges) {
    if (edge.relationship_type !== "includes") continue;
    if (baselineNodeIds.has(edge.source_node_id)) {
      members.add(edge.target_node_id);
    } else if (baselineNodeIds.has(edge.target_node_id)) {
      members.add(edge.source_node_id);
    }
  }
  return members;
}

/**
 * @param {any} node
 * @returns {string}
 */
function familyOf(node) {
  return node?.metadata?.family || node?.metadata?.control_family || "";
}

/**
 * @param {any} options
 * @param {{ nodes?: any[], edges?: any[], sources?: { sources?: any[] } }} dataset
 */
/**
 * Build the structured template document (title + description + typed
 * sections) without serializing it. Shared by the string formatters
 * (markdown/csv/json/yaml via {@link generateTemplate}) and the client-side
 * office serializers (xlsx/docx), so every format renders from one source of
 * truth.
 *
 * @param {any} options
 * @param {any} dataset
 * @returns {{ doc: any, templateType: string, frameworkResolutionError: string | null }}
 */
export function buildTemplateDocument(options, dataset) {
  const normalized = {
    ...options,
    includeSourceFootnotes: true,
    includePlaceholders: options.includePlaceholders !== false,
    includeImplementationPrompts: options.includeImplementationPrompts !== false,
    includeEvidenceExpectations: options.includeEvidenceExpectations !== false,
    includeInheritancePrompts: options.includeInheritancePrompts !== false,
    includeReciprocityPrompts: options.includeReciprocityPrompts !== false,
    includeStigReferences: options.includeStigReferences !== false,
    includeEnhancements: options.includeEnhancements === true,
    environment: options.environment || "Generic",
    sourceRefs: options.sourceRefs || [],
    sources: options.sources || dataset?.sources || [],
  };

  let controls = [];
  let unresolvedFramework = false;
  let unrecognizedBaseline = false;
  if (normalized.framework) {
    // Resolve the raw control nodes for the framework, either directly or (for
    // catalogs that only carry `baseline` nodes, e.g. fedramp-rev5) via
    // baseline-membership edges.
    let controlNodes = collectCatalogControls(dataset.nodes, normalized.framework);
    let resolvedViaBaselineEdges = false;
    if (controlNodes.length === 0) {
      controlNodes = resolveControlsViaBaselineEdges(dataset, normalized.framework);
      resolvedViaBaselineEdges = controlNodes.length > 0;
    }

    if (controlNodes.length === 0) {
      unresolvedFramework = true;
    } else {
      // Optional baseline filter (Low / Moderate / High / ...).
      let baselineApplied = false;
      if (normalized.baseline) {
        const memberIds = collectBaselineMemberIds(
          dataset,
          normalized.baseline,
          normalized.framework,
        );
        if (memberIds.size > 0) {
          controlNodes = controlNodes.filter((n) => memberIds.has(n.id));
          baselineApplied = true;
        } else {
          // Keep the full-catalog fallback, but never silently — the Baseline
          // Notice section below tells the reader what happened.
          unrecognizedBaseline = true;
        }
      }
      // Without a baseline scoping the set, the full catalog's ~900 control
      // enhancements (item_id "AC-2.1" style) drown the base controls — drop
      // them unless explicitly requested. A baseline (including catalogs
      // resolved via baseline-membership edges) legitimately names specific
      // enhancements, so its members pass through untouched.
      if (!baselineApplied && !resolvedViaBaselineEdges && !normalized.includeEnhancements) {
        controlNodes = controlNodes.filter(
          (n) => !String(n.metadata?.item_id || n.id).includes("."),
        );
      }
      // Optional control-family filter (matched case-insensitively against the
      // family name or the control ID prefix, e.g. "Access Control" or "AC").
      if (normalized.controlFamily) {
        const wanted = String(normalized.controlFamily).toLowerCase();
        controlNodes = controlNodes.filter((n) => {
          const fam = familyOf(n).toLowerCase();
          const prefix = String(n.metadata?.item_id || n.id)
            .split("-")[0]
            .toLowerCase();
          return fam === wanted || prefix === wanted || fam.includes(wanted);
        });
      }

      // Natural (numeric-aware) order so control IDs read AC-1, AC-2, AC-10 —
      // not the lexicographic AC-1, AC-10, AC-2 of the raw catalog. Item IDs
      // already encode the family prefix, so this also keeps families grouped.
      controlNodes.sort((a, b) =>
        String(a.metadata?.item_id || a.id).localeCompare(
          String(b.metadata?.item_id || b.id),
          undefined,
          { numeric: true, sensitivity: "base" },
        ),
      );

      // A framework that resolved control nodes but whose baseline/family
      // filter excluded them all falls through to the placeholder row below —
      // the framework itself is not "unresolved".
      controls = controlNodes.map((n) => ({
        nodeId: n.id,
        id: n.metadata?.item_id || n.id,
        title: n.metadata?.title || n.label || n.id,
        family: familyOf(n),
        plain: n.plain_language_summary || "",
      }));
    }
  }
  if (controls.length === 0 && !unresolvedFramework) {
    controls = [{ nodeId: null, id: "[Control ID]", title: "[Control Title]", family: "[Family]" }];
  }

  const frameworkNoticeText = unresolvedFramework
    ? `No control data is ingested for ${normalized.framework} yet — generation unavailable.`
    : null;
  if (unresolvedFramework) {
    controls = [{ id: "[Control ID]", title: "[Control Title]", family: "[Family]" }];
  }

  // Cross-reference index (control → CCI → STIG/SRG) is only needed by the two
  // templates that cite real rule/CCI IDs; build it lazily to avoid the edge
  // scan for the other seven.
  const needsCrossRef =
    normalized.templateType === "evidence_expectation_matrix" ||
    normalized.templateType === "security_plan_starter";
  const crossRef = needsCrossRef ? buildControlCrossRefIndex(dataset) : null;

  let doc;
  switch (normalized.templateType) {
    case "security_plan_starter":
      doc = generateSecurityPlanStarter(normalized, controls, crossRef);
      break;
    case "implementation_statement_worksheet":
      doc = generateImplementationStatementWorksheet(normalized, controls);
      break;
    case "evidence_expectation_matrix":
      doc = generateEvidenceExpectationMatrix(normalized, controls, crossRef);
      break;
    case "stig_evidence_checklist":
      doc = generateSTIGEvidenceChecklist(normalized);
      break;
    case "inheritance_worksheet":
      doc = generateInheritanceWorksheet(normalized, controls);
      break;
    case "reciprocity_checklist":
      doc = generateReciprocityChecklist(normalized);
      break;
    case "poam_starter":
      doc = generatePOAMStarter(normalized);
      break;
    case "assessment_planning_worksheet":
      doc = generateAssessmentPlanningWorksheet(normalized, controls);
      break;
    case "conmon_calendar":
      doc = generateConMonCalendar(normalized);
      break;
    default:
      doc = generateSecurityPlanStarter(normalized, controls, crossRef);
  }

  if (unrecognizedBaseline) {
    doc.sections.unshift({
      type: "text",
      heading: "Baseline Notice",
      content: `Baseline "${normalized.baseline}" was not recognized for ${normalized.framework} — this template includes the full catalog. Valid values include LOW, MODERATE, HIGH.`,
    });
  }

  if (frameworkNoticeText) {
    doc.sections.unshift({
      type: "text",
      heading: "Framework Data Notice",
      content: frameworkNoticeText,
    });
  }

  return {
    doc,
    templateType: normalized.templateType,
    frameworkResolutionError: unresolvedFramework ? frameworkNoticeText : null,
  };
}

/**
 * Compose the download filename for a generated template.
 *
 * @param {string} templateType
 * @param {string} extension
 * @returns {string}
 */
export function templateFilename(templateType, extension) {
  const date = new Date().toISOString().split("T")[0];
  return `${templateType.replace(/_/g, "-")}-${date}.${extension}`;
}

/**
 * Serialize a template to one of the text/data formats (markdown, csv, json,
 * yaml). Office formats (xlsx/docx) are rendered client-side from
 * {@link buildTemplateDocument} — they do not flow through here because their
 * payload is binary, not a string.
 */
export function generateTemplate(options, dataset) {
  const { doc, templateType, frameworkResolutionError } = buildTemplateDocument(
    options,
    dataset,
  );

  let content;
  let extension;
  let mimeType;

  switch (options.format) {
    case "csv":
      content = formatCsv(doc);
      extension = "csv";
      mimeType = "text/csv";
      break;
    case "json":
      content = formatJson(doc);
      extension = "json";
      mimeType = "application/json";
      break;
    case "yaml":
      content = formatYaml(doc);
      extension = "yaml";
      mimeType = "text/yaml";
      break;
    case "markdown":
    default:
      content = formatMarkdown(doc);
      extension = "md";
      mimeType = "text/markdown";
      break;
  }

  return {
    content,
    filename: templateFilename(templateType, extension),
    mimeType,
    frameworkResolutionError,
  };
}
